### ISSUE TITLE
Accuracies are 0 for all sparisty algorithms on ruler_niah task!

### ISSUE THREAD

**Issue by xiehuanyi** [PiotrNawrot/sparse-frontier#2]
Hi, I've ran into another problem! I found that all accuracies are zoros! 
I used this command:
```bash
python -m sparse_frontier.main task=ruler_niah model=qwen_1_5b attention=dense samples=100 gpus=1
python -m sparse_frontier.main task=ruler_niah model=qwen_1_5b attention=ada_snapkv samples=100 gpus=1
python -m sparse_frontier.main task=ruler_niah model=qwen_1_5b attention=block_sparse samples=100 gpus=1
python -m sparse_frontier.main task=ruler_niah model=qwen_1_5b attention=flexprefill samples=100 gpus=1
python -m sparse_frontier.main task=ruler_niah model=qwen_1_5b attention=quest samples=100 gpus=1
python -m sparse_frontier.main task=ruler_niah model=qwen_1_5b attention=snapkv samples=100 gpus=1
python -m sparse_frontier.main task=ruler_niah model=qwen_1_5b attention=vertical_and_slash samples=100 gpus=1
```
and my qwen_1_5b config file is like this:
```
# @package _global_

model:
  name: qwen_1_5b
  path: Qwen/Qwen2.5-1.5B
  num_q_heads: 12
  num_kv_heads: 2
  num_layers: 28
  hidden_dim: 1536
  intermediate_dim: 8960
  vocab_size: 152064

tp: 1
```
And the results are almost the same.
```json
{
    "accuracy": 0.0,
    "accuracy_variance": 0.0,
    "total_samples": 100,
    "average_attention_sparsity": 0.8738517826795578,
    "average_output_tokens": 2048.0,
    "max_output_tokens": 2048
}
```

It's so wired to have accuracy and accuracy_variance are both 0. Could you please provide some suggestions on fixing this?
